DressZone/DressZone.Server/Areas/Admin/Controllers/CartController.cs
using DressZone.Context.Contracts;
using DressZone.Models.Account;
using DressZone.Models.Shop;
using DressZone.Repository.Contracts;
using DressZone.Server.Areas.Admin.Models.ViewModels.Carts;
using DressZone.Server.Infrastructure.Mapping.Contracts;
using DressZone.Services.Contracts;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DressZone.Server.Areas.Admin.Controllers
{
    public class CartController : AdminBaseController
    {
        private IAdminCartService cartService;
        private IAdminUserService userService;

        public CartController(IAdminCartService service, IAdminUserService userService)
        {
            this.cartService = service;
            this.userService = userService;
        }

        public ActionResult CreateCartInitial(string UserName)
        {
            cartService.CreateInitialUserCart(UserName);
            return RedirectToAction("Index", "Home", new { area = string.Empty });
        }

        [HttpGet]
        public ActionResult All()
        {
            return View();
        }

        [HttpPost]
        public ActionResult All([DataSourceRequest]DataSourceRequest model)
        {
            var result = this.cartService.AllCarts().To<AllCartsGridViewModel>().ToList();

            return Json(result.ToDataSourceResult(model));
        }

        [HttpPost]
        public ActionResult UpdateExisting([DataSourceRequest]DataSourceRequest request, AllCartsGridViewModel cartModel)
        {
            if (!this.ModelState.IsValid)
            {
                return Json(new[] { cartModel }.ToDataSourceResult(request, ModelState));
            }

            var cartToUpdate = this.Mapper.Map<Cart>(cartModel);

            var result = this.cartService.UpdateCart(cartToUpdate);

            return Json(new[] { result }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Delete([DataSourceRequest]DataSourceRequest request, AllCartsGridViewModel cartModel)
        {
            var cartToDelete = this.Mapper.Map<Cart>(cartModel);
            this.cartService.DeleteCart(cartToDelete);
            return Json(new[] { cartModel }.ToDataSourceResult(request, ModelState));
        }
    }
}

DressZone/DressZone.Server/Areas/Admin/Controllers/UserController.cs
using DressZone.Server.Areas.Admin.Models.ViewModels.Users;
using DressZone.Server.Infrastructure.Mapping.Contracts;
using DressZone.Services.Contracts;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DressZone.Models.Account;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Security;

namespace DressZone.Server.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : AdminBaseController
    {
        private IAdminUserService userService;

        public UserController(IAdminUserService service)
        {
            this.userService = service;
        }

        [HttpGet]
        public ActionResult All()
        {
            return View();
        }


        [HttpPost]
        public ActionResult All([DataSourceRequest]DataSourceRequest categoriesModel)
        {
            if (!this.ModelState.IsValid)
            {
                return Json(new[] { categoriesModel }.ToDataSourceResult(categoriesModel));
            }
            var allUsers = this.userService.GetAll().To<GridViewUserViewModel>().ToList();
            foreach (var user in allUsers)
            {
                user.Role = this.userService.GetRole(user.Email).Name;
            }
            return Json(allUsers.ToDataSourceResult(categoriesModel));
        }

        [HttpPost]
        public ActionResult Create()
        {
            return null;
        }

        [HttpPost]
        public ActionResult UpdateExisting([DataSourceRequest]DataSourceRequest request, GridViewUserViewModel userModel)
        {
            if (!this.ModelState.IsValid)
            {
                return Json(new[] { userModel }.ToDataSourceResult(request));
            }
            var currentRole = this.userService.GetRole(userModel.Email);
            var userFromDb = userService.GetByEmail(userModel.Email);

            var userManager = this.HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            userManager.RemoveFromRole(userFromDb.Id, currentRole.Name);
            userManager.AddToRole(userFromDb.Id, userModel.Role);
            userFromDb.IsDeleted = userModel.IsDeleted;
            userFromDb.ModifiedOn = DateTime.Now;


            userFromDb = this.userService.EditUser(userFromDb);
           
            var resultViewModel = this.Mapper.Map<GridViewUserViewModel>(userFromDb);
            resultViewModel.Role = this.userService.GetRole(resultViewModel.Email).Name;

            var result = new[] { resultViewModel }.ToDataSourceResult(request, ModelState);
            return Json(result);

        }

        [HttpPost]
        public ActionResult Delete([DataSourceRequest]DataSourceRequest request, GridViewUserViewModel categoryModel)
        {
            var userToDelete = this.userService.GetByEmail(categoryModel.Email);
            var deletedUser = this.userService.Delete(userToDelete);
            var result = new[] { deletedUser }.ToDataSourceResult(request, ModelState);
            return Json(result);
        }
    }
}

DressZone/DressZone.Server/Views/Shared/FeaturedProducts.cshtml
@model IEnumerable<DressZone.Server.Models.DTO.Home.HomeCategoryDTO>
<div class="container">

    @foreach (var category in Model)
    {
        <div class="one-third column">
            <a href="/AllCategories/All" class="img-caption">
                <figure>
                    <img src="~/images/Uploaded/Categories/@category.FrontImageName" alt="@category.Description" />
                    <figcaption>
                        <h3>@category.Name</h3>
                        <span>@category.Description</span>
                    </figcaption>
                </figure>
            </a>
        </div>
    }
</div>
<div class="clearfix"></div>

DressZone/DressZone.Server/Views/Shared/Footer.cshtml
<div id="footer">

    <!-- Container -->
    <div class="container">

        <div class="four columns">
            <img src="~/images/logo.png" alt="" class="margin-top-10" />
        </div>

        <div class="four columns">

            <!-- Headline -->
            <h3 class="headline footer">Customer Service</h3>
            <span class="line"></span>
            <div class="clearfix"></div>

            <ul class="footer-links">
                <li><a href="#">Order Status</a></li>
                <li><a href="#">Payment Methods</a></li>
                <li><a href="#">Delivery & Returns</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms & Conditions</a></li>
            </ul>

        </div>

        <div class="four columns">

            <!-- Headline -->
            <h3 class="headline footer">My Account</h3>
            <span class="line"></span>
            <div class="clearfix"></div>

            <ul class="footer-links">
                <li><a href="#">My Account</a></li>
                <li><a href="#">Order History</a></li>
                <li><a href="#">Wish List</a></li>
            </ul>

        </div>

        <div class="four columns">

            <!-- Headline -->
            <h3 class="headline footer">Newsletter</h3>
            <span class="line"></span>
            <div class="clearfix"></div>
            <p>Sign up to receive email updates on new product announcements, gift ideas, special promotions, sales and more.</p>

            <form action="#" method="get">
                <button class="newsletter-btn" type="submit">Join</button>
                <input class="newsletter" type="text" placeholder="mail@example.com" value="" />
            </form>
        </div>

    </div>
    <!-- Container / End -->

</div>

DressZone/DressZone.Server/Views/Shared/FooterBottom.cshtml
<div id="footer-bottom">

    <!-- Container -->
    <div class="container">

        <div class="eight columns">© Copyright 2014 <a href="#"></a>. All Rights Reserved.</div>
        <div class="eight columns">
            <ul class="payment-icons">
                <li><img src="~/images/visa.png" alt="" /></li>
                <li><img src="~/images/mastercard.png" alt="" /></li>
                <li><img src="~/images/skrill.png" alt="" /></li>
                <li><img src="~/images/moneybookers.png" alt="" /></li>
                <li><img src="~/images/paypal.png" alt="" /></li>
            </ul>
        </div>

    </div>
    <!-- Container / End -->

</div>

DressZone/DressZone.Server/Views/Shared/Header.cshtml
<div class="container">


    <!-- Logo -->
    <div class="four columns">
        <div id="logo">
            <h1><a href="@Url.Action("Index","Home", new { area = string.Empty })"><img id="imgLogo" src="~/images/logo.png" /></a></h1>
        </div>
    </div>


    <!-- Additional Menu -->
    <div class="twelve columns">
        <div id="additional-menu">
            <ul>
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </div>


    <!-- Shopping Cart -->
    <div class="twelve columns">

        @if (this.Request.IsAuthenticated)
        {
            <div id="cart">

                <!-- Button -->
                <div class="cart-btn">
                    <a href="#" class="button adc"></a>
                </div>

                <div class="cart-list">

                    <div class="arrow"></div>

                    <div class="cart-amount">
                        <span></span>
                    </div>

                    <ul>
                        <li>
                            <a href="#"><img src="" alt="" /></a>
                            <a href="#"></a>
                            <span></span>
                            <div class="clearfix"></div>
                        </li>

                        <li>
                            <a href="#"><img src="" alt="" /></a>
                            <a href="#">Tommy Hilfiger <br /> Shirt Beat</a>
                            <span></span>
                            <div class="clearfix"></div>
                        </li>
                    </ul>

                    <div class="cart-buttons button">
                        @Html.ActionLink("View Cart", "Details", "CartView",new {area = "UserArea" },new { @class = "view-cart" })
                        <a href="/Checkout/Index" class="checkout"><span data-hover="Checkout">Checkout</span></a>
                    </div>
                    <div class="clearfix">

                    </div>
                </div>

            </div>
        }
        

        <!-- Search -->
        <nav class="top-search">
            <form action="#" method="get">
                <button><i class="fa fa-search"></i></button>
                <input class="search-field" type="text" placeholder="Search" value="" />
            </form>
        </nav>

    </div>

</div>
@section scripts{
    <section>

    </section>
    }

DressZone/DressZone.Server/Views/Shared/Navigation.cshtml
<div class="container">
    <div class="sixteen columns">

        <a href="#menu" class="menu-trigger"><i class="fa fa-bars"></i> Menu</a>

        <nav id="navigation">
            <ul class="menu" id="responsive">

                <li><a href="index.html" class="current homepage" id="current">Home</a></li>

                <li class="dropdown">
                    <a href="#">Shop</a>
                    <ul>
                        <li>@Html.ActionLink("Categories","Details","CategoriesDetails",new { area = "" })</li>
                    </ul>
                </li>

                @if (this.User.IsInRole("Admin"))
                {
                    <li>
                        <a href="#">Admin Features</a>
                        <div class="mega">
                            <div class="mega-container">

                                <div class="one-column">
                                    <ul>
                                        <li><span class="mega-headline">Manage Categories</span></li>
                                        <li>@Html.ActionLink("ManageAll", "All", "Categories", new { area = "Admin" }, null)</li>
                                        <li>@Html.ActionLink("Create Category", "AddCategory", "Categories", new { area = "Admin" }, null)</li>
                                    </ul>
                                </div>

                                <div class="one-column">
                                    <ul>
                                        <li><span class="mega-headline">Manage Products</span></li>
                                        <li>@Html.ActionLink("ManageAll", "All", "ProductsCreate", new { area = "Admin" }, null)</li>
                                        <li>@Html.ActionLink("AddImages", "AddImages", "ProductImages", new { area = "Admin" }, null)</li>

                                    </ul>
                                </div>
                                <div class="one-column">
                                    <ul>
                                        <li><span class="mega-headline">Manage Users</span></li>
                                        <li>@Html.ActionLink("ManageAll", "All", "User", new { area = "Admin" }, null)</li>
                                    </ul>
                                </div>
                                <div class="one-column">
                                    <ul>
                                        <li><span class="mega-headline">Manage Carts</span></li>
                                        <li>@Html.ActionLink("ManageAll", "All", "Cart", new { area = "Admin" }, null)</li>

                                    </ul>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

DressZone/DressZone.Server/Views/Shared/NewArrivals.cshtml
@model IEnumerable<DressZone.Server.Models.DTO.Home.HomeProductDTO>
<div class="container">

    <!-- Headline -->
    <div class="sixteen columns">
        <h3 class="headline">New Arrivals</h3>
        <span class="line margin-bottom-0"></span>
    </div>

    <!-- Carousel -->
    <div id="new-arrivals" class="showbiz-container sixteen columns">

        <!-- Navigation -->
        <div class="showbiz-navigation">
            <div id="showbiz_left_1" class="sb-navigation-left"><i class="fa fa-angle-left"></i></div>
            <div id="showbiz_right_1" class="sb-navigation-right"><i class="fa fa-angle-right"></i></div>
        </div>
        <div class="clearfix"></div>

        <!-- Products -->
        <div class="showbiz" data-left="#showbiz_left_1" data-right="#showbiz_right_1" data-play="#showbiz_play_1">
            <div class="overflowholder">

                <ul>
                    @foreach (var product in Model)
                    {

                        var imageName = product.CategoryName + "/" + product.FileName;
                    <!-- Product #1 -->
                        <li>
                            <figure class="product">
                                <div class="mediaholder">
                                    <a href="/ProductDetails/Details/@product.Id">
                                        <img alt="" src="~/images/Uploaded/@product.CategoryName/@product.FileName" />
                                        <div class="cover">
                                            <img alt="" src="~/images/Uploaded/@imageName" />
                                        </div>
                                    </a>
                                    <a href="#" class="product-button"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
                                </div>

                                <a href="variable-product-page.html">
                                    <section>
                                        <span class="product-category">@product.CategoryName</span>
                                        <h5>@product.Title</h5>
                                        <span class="product-price">$@product.Price</span>
                                    </section>
                                </a>
                            </figure>
                        </li>

                    }

                </ul>
                <div class="clearfix"></div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>

</div>

DressZone/DressZone.Server/Views/Shared/Parallax.cshtml
<div class="parallax-banner" data-background="#000" data-opacity="0.45" data-height="200">
    <img src="~/images/Uploaded/sliderIndex/clark-slider.jpg" alt="" />
    <div class="parallax-overlay"></div>
    <div class="parallax-title">End of season sale <span>Up to 35% off Women’s Denim</span></div>
</div>

DressZone/DressZone.Server/Views/Shared/ProductLists.cshtml
<div class="container margin-bottom-25">

    <!-- Best Sellers -->
    <div class="one-third column">

        <!-- Headline -->
        <h3 class="headline">Best Sellers</h3>
        <span class="line margin-bottom-0"></span>
        <div class="clearfix"></div>


        <ul class="product-list">

            <li>
                <a href="#">
                    <img src="images/small_product_list_01.jpg" alt="" />
                    <div class="product-list-desc">Canvas Backpack <i>$59.00</i></div>
                </a>
            </li>

            <li><div class="clearfix"></div></li>

        </ul>

    </div>


    <!-- Top Rated -->
    <div class="one-third column">

        <!-- Headline -->
        <h3 class="headline">Top Rated</h3>
        <span class="line margin-bottom-0"></span>
        <div class="clearfix"></div>


        <ul class="product-list top-rated">

            <li>
                <a href="#">
                    <img src="images/small_product_list_04.jpg" alt="" />
                    <div class="product-list-desc with-rating">
                        Brogue Boots in Leather <i>$99.00</i>
                        <div class="rating five-stars">
                            <div class="star-rating"></div>
                            <div class="star-bg"></div>
                        </div>
                    </div>
                </a>
            </li>

            <li><div class="clearfix"></div></li>

        </ul>

    </div>


    <!-- Weekly Sales -->
    <div class="one-third column">

        <!-- Headline -->
        <h3 class="headline">Weekly Sales</h3>
        <span class="line margin-bottom-0"></span>
        <div class="clearfix"></div>


        <ul class="product-list discount">

            <li>
                <a href="#">
                    <img src="images/small_product_list_07.jpg" alt="" />
                    <div class="product-list-desc">Short Sleeve Polo Shirt <i>$29.00<b>$19.00</b></i></div>
                </a>
            </li>


            <li><div class="clearfix"></div></li>

        </ul>

    </div>

</div>

DressZone/DressZone.Server/Views/Shared/Slider.cshtml
<div class="container home-slider">

    <div class="tp-banner-container">
        <div class="tp-banner">
            <ul>
                <!-- Slide 1  -->
                <li data-transition="fade" data-slotamount="7" data-masterspeed="1500">
                    <img src="~/images/Uploaded/sliderIndex/boots-jeans-slider.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                    <div class="caption sfb fadeout" data-x="145" data-y="170" data-speed="400" data-start="800" data-easing="Power4.easeOut">
                        <h2>Dress Sharp</h2>
                        <h3>Learn from the classics</h3>
                        <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a>
                    </div>
                </li>

                <!-- Slide 2  -->
                <li data-transition="zoomout" data-slotamount="7" data-masterspeed="1000">
                    <img src="~/images/Uploaded/sliderIndex/bag-shoes-woman.jpg" alt="darkblurbg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                    <div class="caption dark sfb fadeout" data-x="750" data-y="170" data-speed="400" data-start="800" data-easing="Power4.easeOut">
                        <h2>Urban Style</h2>
                        <h3>Every cut and colour</h3>
                        <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a>
                    </div>
                </li>

                <!-- Slide 3  -->
                <li data-transition="fadetotopfadefrombottom" data-slotamount="7" data-masterspeed="1000">
                    <img src="~/images/Uploaded/sliderIndex/boots3.jpg" alt="darkblurbg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                    <div class="caption dark sfb fadeout" data-x="850" data-y="170" data-speed="400" data-start="800" data-easing="Power4.easeOut">
                        <h2>New In</h2>
                        <h3>Pants and T-Shirts</h3>
                        <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a>
                    </div>
                </li>

                <!-- Slide 3  -->
                <li data-transition="fadetotopfadefrombottom" data-slotamount="7" data-masterspeed="1000">
                    <img src="~/images/Uploaded/sliderIndex/adidas-slider.jpg" alt="darkblurbg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                    <div class="caption dark sfb fadeout" data-x="850" data-y="170" data-speed="400" data-start="800" data-easing="Power4.easeOut">
                        <h2>New In</h2>
                        <h3>Pants and T-Shirts</h3>
                        <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a>
                    </div>
                </li>

            </ul>
        </div>
    </div>
</div>

DressZone/DressZone.Server/Views/Shared/StyleSwitcher.cshtml
<div id="style-switcher">
    <h2>Style Switcher <a href="#"></a></h2>

    <div>
        <h3>Predefined Colors</h3>
        <ul class="colors" id="color1">
            <li><a href="#" class="green" title="Green"></a></li>
            <li><a href="#" class="blue" title="Blue"></a></li>
            <li><a href="#" class="orange" title="Orange"></a></li>
            <li><a href="#" class="navy" title="Navy"></a></li>
            <li><a href="#" class="yellow" title="Yellow"></a></li>
            <li><a href="#" class="peach" title="Peach"></a></li>
            <li><a href="#" class="beige" title="Beige"></a></li>
            <li><a href="#" class="purple" title="Purple"></a></li>
            <li><a href="#" class="celadon" title="Celadon"></a></li>
            <li><a href="#" class="pink" title="Pink"></a></li>
            <li><a href="#" class="red" title="Red"></a></li>
            <li><a href="#" class="brown" title="Brown"></a></li>
            <li><a href="#" class="cherry" title="Cherry"></a></li>
            <li><a href="#" class="cyan" title="Cyan"></a></li>
            <li><a href="#" class="gray" title="Gray"></a></li>
            <li><a href="#" class="darkcol" title="Dark"></a></li>
        </ul>

        <h3>Layout Style</h3>
        <div class="layout-style">
            <select id="layout-style">
                <option value="1">Boxed</option>
                <option value="2">Wide</option>
            </select>
        </div>

        <h3>Background Image</h3>
        <ul class="colors bg" id="bg">
            <li><a href="#" class="bg1"></a></li>
            <li><a href="#" class="bg2"></a></li>
            <li><a href="#" class="bg3"></a></li>
            <li><a href="#" class="bg4"></a></li>
            <li><a href="#" class="bg5"></a></li>
            <li><a href="#" class="bg6"></a></li>
            <li><a href="#" class="bg7"></a></li>
            <li><a href="#" class="bg8"></a></li>
            <li><a href="#" class="bg9"></a></li>
            <li><a href="#" class="bg10"></a></li>
            <li><a href="#" class="bg11"></a></li>
            <li><a href="#" class="bg12"></a></li>
            <li><a href="#" class="bg13"></a></li>
            <li><a href="#" class="bg14"></a></li>
            <li><a href="#" class="bg15"></a></li>
            <li><a href="#" class="bg16"></a></li>
        </ul>

        <h3>Background Color</h3>
        <ul class="colors bgsolid" id="bgsolid">
            <li><a href="#" class="green-bg" title="Green"></a></li>
            <li><a href="#" class="blue-bg" title="Blue"></a></li>
            <li><a href="#" class="orange-bg" title="Orange"></a></li>
            <li><a href="#" class="navy-bg" title="Navy"></a></li>
            <li><a href="#" class="yellow-bg" title="Yellow"></a></li>
            <li><a href="#" class="peach-bg" title="Peach"></a></li>
            <li><a href="#" class="beige-bg" title="Beige"></a></li>
            <li><a href="#" class="purple-bg" title="Purple"></a></li>
            <li><a href="#" class="red-bg" title="Red"></a></li>
            <li><a href="#" class="pink-bg" title="Pink"></a></li>
            <li><a href="#" class="celadon-bg" title="Celadon"></a></li>
            <li><a href="#" class="brown-bg" title="Brown"></a></li>
            <li><a href="#" class="cherry-bg" title="Cherry"></a></li>
            <li><a href="#" class="cyan-bg" title="Cyan"></a></li>
            <li><a href="#" class="gray-bg" title="Gray"></a></li>
            <li><a href="#" class="dark-bg" title="Dark"></a></li>
        </ul>
    </div>

    <div id="reset"><a href="#" class="button color">Reset</a></div>

</div>

DressZone/DressZone.Server/Views/Shared/TopBar.cshtml
<div id="top-bar">
    <div class="container">

        <!-- Top Bar Menu -->


    </div>
</div>

DressZone/DressZone.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <title>DressZone</title>

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- CSS
    ================================================== -->
    @*<link rel="stylesheet" href="Content/style.css">*@
    @*<link rel="stylesheet" href="Content/green.css" id="colors">*@
    
    @Styles.Render("~/Content/css")
    @Styles.Render("~/kendo/styles")
    <!-- Initial JS-->
    <script src="~/Scripts/themeScripts/jquery-1.11.0.min.js"></script>
    <script src="~/Scripts/themeScripts/jquery-migrate-1.2.1.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("kendo", required: false)


    @* @Scripts.Render("~/bundles/jquery11")*@
    @* @Scripts.Render("~/bundles/jquerymigrate")*@
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<body class="boxed">
    <div id="wrapper">


        <!-- Top Bar
        ================================================== -->
        @Html.Partial("TopBar")

        <div class="clearfix"></div>


        <!-- Header
        ================================================== -->
        @Html.Partial("Header")


        <!-- Navigation
        ================================================== -->
        @Html.Partial("Navigation")
       
        <div class="container body-content">
            @RenderBody()

        </div>
        <div class="margin-top-50"></div>

        <!-- Footer
        ================================================== -->
      @Html.Partial("Footer")
        <!-- Footer / End -->
        <!-- Footer Bottom / Start -->
       @Html.Partial("FooterBottom")
        <!-- Footer Bottom / End -->
        <!-- Back To Top Button -->
        <div id="backtotop"><a href="#"></a></div>

        <!-- Java Script
        ================================================== -->
        @*<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>*@


        <script src="~/Scripts/themeScripts/jquery.jpanelmenu.js"></script>
        <script src="~/Scripts/themeScripts/jquery.themepunch.plugins.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.themepunch.revolution.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.themepunch.showbizpro.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.magnific-popup.min.js"></script>
        <script src="~/Scripts/themeScripts/hoverIntent.js"></script>
        <script src="~/Scripts/themeScripts/superfish.js"></script>
        <script src="~/Scripts/themeScripts/jquery.pureparallax.js"></script>
        <script src="~/Scripts/themeScripts/jquery.pricefilter.js"></script>
        <script src="~/Scripts/themeScripts/jquery.selectric.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.royalslider.min.js"></script>
        <script src="~/Scripts/themeScripts/SelectBox.js"></script>
        <script src="~/Scripts/themeScripts/modernizr.custom.js"></script>
        <script src="~/Scripts/themeScripts/waypoints.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.flexslider-min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.counterup.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.tooltips.min.js"></script>
        <script src="~/Scripts/themeScripts/jquery.isotope.min.js"></script>
        <script src="~/Scripts/themeScripts/puregrid.js"></script>
        <script src="~/Scripts/themeScripts/stacktable.js"></script>
        <script src="~/Scripts/themeScripts/custom.js"></script>
        @RenderSection("scripts", required: false)
        @Scripts.Render("~/bundles/private-functions");
        <!-- Style Switcher
        ================================================== -->
        <script src="~/Scripts/themeScripts/switcher.js"></script>

        @Html.Partial("StyleSwitcher")
    </div>

</body>
</html>